const sampleList: Sample[] = [
  {
    hashId: "sample1",
    sampleType: "Water",
    location: { lat: -1.4558, lng: -48.4902 },
    DNASequenceFiles: [
      { url: "https://example.com/sample1/file1" },
      { url: "https://example.com/sample1/file2" },
    ],
    MolecularMarkers: ["18S", "COI"],
    CollectionDate: "2021-01-15",
    creditId: "1",
    DAPC: [{ "Group 1": 80 }, { "Group 2": 15 }, { "Group 3": 5 }],
  },
  {
    hashId: "sample2",
    sampleType: "Water",
    location: { lat: -1.4558, lng: -48.4902 },
    DNASequenceFiles: [
      { url: "https://example.com/sample2/file1" },
      { url: "https://example.com/sample2/file2" },
    ],
    MolecularMarkers: ["ITS", "rbcL"],
    CollectionDate: "2021-02-20",
    creditId: "1",
    DAPC: [{ "Group 1": 70 }, { "Group 2": 20 }, { "Group 3": 10 }],
  },
  {
    hashId: "sample3",
    sampleType: "Soil",
    location: { lat: -5.3807, lng: -49.1327 },
    DNASequenceFiles: [
      { url: "https://example.com/sample3/file1" },
      { url: "https://example.com/sample3/file2" },
    ],
    MolecularMarkers: ["12S", "16S"],
    CollectionDate: "2021-03-25",
    creditId: "1",
    DAPC: [{ "Group 1": 60 }, { "Group 2": 30 }, { "Group 3": 10 }],
  },
  {
    hashId: "sample4",
    sampleType: "Water",
    location: { lat: -3.2041, lng: -52.2066 },
    DNASequenceFiles: [
      { url: "https://example.com/sample4/file1" },
      { url: "https://example.com/sample4/file2" },
    ],
    MolecularMarkers: ["18S", "COI"],
    CollectionDate: "2021-04-30",
    creditId: "1",
    DAPC: [{ "Group 1": 50 }, { "Group 2": 40 }, { "Group 3": 10 }],
  },
  {
    hashId: "sample5",
    sampleType: "Soil",
    location: { lat: -6.0678, lng: -49.9037 },
    DNASequenceFiles: [
      { url: "https://example.com/sample5/file1" },
      { url: "https://example.com/sample5/file2" },
    ],
    MolecularMarkers: ["ITS", "rbcL"],
    CollectionDate: "2021-05-05",
    creditId: "1",
    DAPC: [{ "Group 1": 40 }, { "Group 2": 50 }, { "Group 3": 10 }],
  },
  {
    hashId: "sample6",
    sampleType: "Soil",
    location: { lat: -1.2971, lng: -47.9167 },
    DNASequenceFiles: [
      { url: "https://example.com/sample6/file1" },
      { url: "https://example.com/sample6/file2" },
    ],
    MolecularMarkers: ["12S", "16S"],
    CollectionDate: "2021-06-10",
    creditId: "2",
    DAPC: [{ "Group 1": 30 }, { "Group 2": 60 }, { "Group 3": 10 }],
  },
  {
    hashId: "sample7",
    sampleType: "Water",
    location: { lat: -1.0543, lng: -46.7665 },
    DNASequenceFiles: [
      { url: "https://example.com/sample7/file1" },
      { url: "https://example.com/sample7/file2" },
    ],
    MolecularMarkers: ["18S", "COI"],
    CollectionDate: "2021-07-15",
    creditId: "2",
    DAPC: [{ "Group 1": 20 }, { "Group 2": 70 }, { "Group 3": 10 }],
  },
  {
    hashId: "sample8",
    sampleType: "Soil",
    location: { lat: -4.2763, lng: -55.9836 },
    DNASequenceFiles: [
      { url: "https://example.com/sample8/file1" },
      { url: "https://example.com/sample8/file2" },
    ],
    MolecularMarkers: ["ITS", "rbcL"],
    CollectionDate: "2021-08-20",
    creditId: "2",
    DAPC: [{ "Group 1": 10 }, { "Group 2": 80 }, { "Group 3": 10 }],
  },
  {
    hashId: "sample9",
    sampleType: "Soil",
    location: { lat: -3.7654, lng: -49.6726 },
    DNASequenceFiles: [
      { url: "https://example.com/sample9/file1" },
      { url: "https://example.com/sample9/file2" },
    ],
    MolecularMarkers: ["12S", "16S"],
    CollectionDate: "2021-09-25",
    creditId: "2",
    DAPC: [{ "Group 1": 5 }, { "Group 2": 85 }, { "Group 3": 10 }],
  },
  {
    hashId: "sample10",
    sampleType: "Water",
    location: { lat: -8.0253, lng: -50.0317 },
    DNASequenceFiles: [
      { url: "https://example.com/sample10/file1" },
      { url: "https://example.com/sample10/file2" },
    ],
    MolecularMarkers: ["18S", "COI"],
    CollectionDate: "2021-10-30",
    creditId: "2",
    DAPC: [{ "Group 1": 95 }, { "Group 2": 4 }, { "Group 3": 1 }],
  },
];

export default sampleList;
